# Generated by Django 4.1.7 on 2023-04-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tiqueo'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricas',
            name='binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
