# Generated by Django 4.1.7 on 2023-04-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_metricas_binary_metricas_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricas',
            name='array',
        ),
        migrations.AddField(
            model_name='metricas',
            name='binary',
            field=models.BinaryField(blank=True, null=True, verbose_name='Array'),
        ),
    ]
