# Generated by Django 4.1.7 on 2023-05-18 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_permisosgenerales_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=50)),
                ('hoja_vida', models.TextField(verbose_name='Hoja de vida')),
                ('recorrido', models.TextField(verbose_name='Hoja de recorrido')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
