# Generated by Django 4.1.7 on 2023-05-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_kardex_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='ubicacion_actual',
            field=models.CharField(default='potosi', max_length=5000),
            preserve_default=False,
        ),
    ]
