# Generated by Django 4.1.7 on 2023-05-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_kardex_ubicacion_actual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricas',
            options={'permissions': (('users', 'Modulo de usuarios'), ('requerimientos', 'Modulo de requerimientos'))},
        ),
        migrations.AddField(
            model_name='kardex',
            name='indefinido',
            field=models.BooleanField(default=False),
        ),
    ]
