# Generated by Django 4.1.7 on 2023-05-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_metricas_options_kardex_indefinido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kardex',
            options={'permissions': (('users', 'Modulo de Personal'), ('requerimientos', 'Modulo de requerimientos'))},
        ),
    ]
